// Donnees FAQ par role — extraites verbatim de l application actuelle.
export const FAQ = {
  rex: [
    ['Par où je commence ?', 'Suivez les étapes dans l\'ordre de la barre latérale : d\'abord votre objectif de chiffre d\'affaires, puis votre équipe, puis la présence et les heures supplémentaires, et enfin le prévisionnel et la synthèse. À chaque écran, SOMA vous guide et calcule les conséquences de vos choix. Vous n\'avez jamais à tout remplir d\'un coup : vous avancez pas à pas.'],
    ['Comment saisir mes références CA journalières ?', 'Sur l\'écran Objectif, renseignez votre chiffre d\'affaires cible et votre TXR (CA par heure travaillée). SOMA en déduit le besoin en heures semaine par semaine. Ces deux valeurs sont le point de départ de tout le budget : elles déterminent combien de personnel il vous faut.'],
    ['Comment importer mon équipe depuis Excel ?', 'Sur l\'écran Équipe, utilisez la fonction d\'import et déposez votre fichier au format attendu (une matrice d\'import est fournie). SOMA lit les salariés, leurs qualifications et leurs heures. Vous pouvez ensuite ajuster chaque ligne à la main.'],
    ['Que signifient les qualifications (DEA, AA, TAXI, TPMR) ?', 'Ce sont les qualifications du personnel roulant : DEA (diplôme d\'ambulancier), AA (auxiliaire ambulancier), TAXI et TPMR (transport de personnes à mobilité réduite). SOMA les considère comme du personnel roulant, c\'est-à-dire qui produit du chiffre d\'affaires sur la route. Les autres qualifications sont comptées comme personnel improductif.'],
    ['Qu\'est-ce que le pourcentage roulant d\'un salarié ?', 'Certains salariés ne roulent pas à 100% de leur temps : ils partagent leur activité entre la route et la régulation, ou des tâches administratives. Le pourcentage roulant indique la part réellement passée à produire du chiffre d\'affaires. Par exemple, 50% pour une personne mi-roulant, mi-régulation. Le reste est compté comme improductif.'],
    ['Comment fonctionne la répartition automatique des congés ?', 'SOMA répartit vos congés sur l\'année selon deux principes. D\'abord les périodes légales : 60% des congés sur juin-octobre, 20% sur novembre-janvier, 20% sur février-mai. Ensuite le lissage : à l\'intérieur de chaque période, SOMA place les congés de façon à garder un recours aux heures supplémentaires le plus régulier possible, en évitant les semaines déjà tendues.'],
    ['Pourquoi SOMA ne cherche pas à supprimer toutes les heures supplémentaires ?', 'Parce qu\'un budget sans aucune heure supplémentaire est un budget rigide. L\'activité réelle ne sera jamais exactement celle prévue. Une réserve d\'environ 10% d\'heures supplémentaires permet d\'absorber une hausse d\'activité sans basculer dans les heures les plus chères, et une baisse sans dégrader la productivité. Zéro heure supplémentaire n\'est pas un objectif : c\'est une fragilité.'],
    ['Pourquoi distingue-t-on les heures à 25% et à 50% ?', 'Les huit premières heures supplémentaires par semaine et par salarié sont majorées à 25%, au-delà à 50%. Deux agences avec le même volume d\'heures supplémentaires peuvent donc avoir des coûts très différents selon la façon dont ces heures se répartissent. Indiquer la part de vos heures à 50% permet à SOMA de calculer le vrai coût de vos heures supplémentaires.'],
    ['Qu\'est-ce que le coût du choix que je vois en synthèse ?', 'SOMA calcule la répartition des congés qui minimise le coût des heures supplémentaires. Vous pouvez choisir de vous en écarter, par exemple pour accorder des congés à un moment qui compte pour votre équipe. Ce choix a parfois un surcoût. SOMA le chiffre non pour vous en dissuader, mais pour que vous puissiez l\'assumer et le justifier lors de la validation.'],
    ['Comment lire la courbe de charge et les couleurs des semaines ?', 'La courbe montre les heures supplémentaires par personne présente, semaine par semaine. Une courbe plate signifie une charge équitable. Les trois zones colorées correspondent aux périodes légales de congés. Dans le détail des semaines, chaque semaine porte un verdict en langage clair : aucune tension, charge légère, charge soutenue ou surcharge. Une semaine en surcharge mérite votre attention.'],
    ['Pourquoi mon absentéisme doit-il rester proche de la référence ?', 'Le taux d\'absentéisme maladie et accident de travail est calculé par le service RH à partir de l\'historique. C\'est une donnée de référence. Vous pouvez ajuster sa répartition mois par mois selon la réalité de votre agence, mais la moyenne annuelle doit rester proche de cette référence. Sinon votre budget repose sur une hypothèse d\'absentéisme irréaliste.'],
    ['Comment sont calculés les congés générés ?', 'Chaque mois de présence génère environ 2,5 jours de congés payés. SOMA calcule automatiquement le total de congés à écouler sur l\'année à partir de votre effectif et de son temps de présence. C\'est ce stock que la répartition automatique distribue ensuite sur vos semaines.'],
    ['Que veut dire verrouiller un mois ?', 'Verrouiller un mois indique à SOMA que vous avez ajusté ce mois manuellement et qu\'il ne doit plus y toucher lors des répartitions automatiques. Le moteur travaille alors autour de vos mois verrouillés. C\'est utile quand vous savez qu\'un mois particulier doit rester tel que vous l\'avez réglé.'],
    ['Comment anticiper un CDD saisonnier ou un départ ?', 'Dans l\'équipe, renseignez les dates d\'entrée et de sortie de chaque salarié. SOMA tient compte de ces mouvements semaine par semaine : un CDD saisonnier n\'ajoute de la capacité que pendant sa période, un départ la retire à partir de sa date. Votre budget reflète ainsi la réalité de vos effectifs tout au long de l\'année.'],
    ['Comment sont pris en compte les régulateurs et responsables ?', 'Ce sont du personnel improductif : ils ne produisent pas de chiffre d\'affaires sur la route, mais ils ont un coût. SOMA les intègre dans la masse salariale sans les compter dans la capacité roulante. Le bloc dédié sur l\'écran Présence permet de les renseigner. Chaque agence en a, c\'est normal.'],
    ['Comment saisir les indemnités repas et dimanche/jour férié ?', 'Sur l\'écran Présence, le bloc indemnités permet de renseigner, semaine par semaine, les montants pour le personnel roulant et non-roulant. Comme les congés, ce sont des saisies récurrentes qui alimentent votre masse salariale prévisionnelle.'],
    ['Quelle différence entre personnel roulant et improductif ?', 'Le personnel roulant produit du chiffre d\'affaires en transportant des patients : c\'est lui qui génère votre activité. Le personnel improductif (régulateurs, responsables, administratifs) est nécessaire au fonctionnement mais ne roule pas. Les deux ont un coût, seul le roulant produit du CA. C\'est cette distinction qui permet de calculer votre TXR.'],
    ['Comment sauvegarder mon travail ?', 'SOMA sauvegarde automatiquement au fil de votre saisie, en silence. Vous n\'avez pas de bouton à presser. Une petite mention vous confirme l\'enregistrement. Vos données sont conservées sur le serveur et vous les retrouvez à votre prochaine connexion.'],
    ['Comment soumettre mon budget ?', 'Quand votre budget est prêt, utilisez le bouton de soumission. Votre budget entre alors dans le circuit de validation collégial et vous ne pouvez plus le modifier tant qu\'il est en cours de validation. Assurez-vous d\'avoir vérifié votre synthèse avant de soumettre.'],
    ['Mon budget a été refusé, que faire ?', 'Si un validateur refuse votre budget, il revient à l\'état brouillon et vous pouvez de nouveau le modifier. Un bandeau sur votre écran vous indique qui a refusé et pour quel motif. Corrigez ce qui est signalé, puis resoumettez : un nouveau cycle de validation démarre alors depuis le début.'],
  ],
  cg: [
    ['Quel est mon rôle dans SOMA ?', 'Le contrôleur de gestion prépare le terrain et supervise le réseau. Vous renseignez les données de référence de chaque agence (historiques, statistiques, cibles), vous suivez l\'avancement des 27 budgets, vous les comparez, et vous participez à leur validation. Vous êtes aussi valideur : votre décision compte dans le circuit collégial.'],
    ['Comment bien préparer les références des agences ?', 'Avant que les responsables construisent leurs budgets, vous posez leur cadre : le CA historique, le TXR de référence, le taux d\'absentéisme maladie et accident de travail. Ces données servent de socle et de point de comparaison. Plus elles sont justes, plus les budgets des agences seront réalistes et faciles à juger.'],
    ['Que dois-je vérifier avant que les responsables construisent leurs budgets ?', 'Assurez-vous que chaque agence a ses données de référence renseignées et qu\'un directeur régional lui est affecté. Sans référence, le responsable construit à l\'aveugle. Sans DR affecté, son budget ne pourra pas être validé à la première étape du circuit. L\'écran d\'affectation vous montre où il manque quelque chose.'],
    ['Comment pré-remplir les données de toutes les agences ?', 'Utilisez la fonction d\'import des références : une matrice permet de renseigner en une fois les données de plusieurs agences, plutôt que de les saisir une par une. C\'est le plus gros gain de temps pour préparer le réseau. Vous pouvez ensuite ajuster agence par agence.'],
    ['Comment importer le registre RH ?', 'La fonction d\'import RH permet de charger les données du personnel de plusieurs agences depuis un fichier. SOMA répartit les salariés dans leur agence respective. Vous évitez ainsi de ressaisir manuellement chaque équipe.'],
    ['Comment suivre l\'avancement des 27 agences ?', 'Le tableau de bord réseau vous montre l\'état de chaque agence : budget non commencé, en cours, soumis, validé. Vous voyez d\'un coup d\'œil qui a soumis et qui est en retard, sans avoir à ouvrir chaque agence.'],
    ['Comment repérer une agence qui sort de l\'ordinaire ?', 'SOMA compare chaque agence à la médiane du réseau et signale les écarts notables. Une agence dont un indicateur s\'éloigne fortement de ses pairs est mise en évidence. Cela vous permet de concentrer votre attention sur les budgets qui le méritent, plutôt que de tout éplucher.'],
    ['À quoi sert la vue comparative ?', 'Elle met les agences côte à côte sur les mêmes indicateurs, pour repérer les atypies. Une agence n\'est jamais bonne ou mauvaise dans l\'absolu : elle l\'est par rapport à ses pairs et à son contexte. La vue comparative vous donne cette lecture relative.'],
    ['À quoi servent les graphiques ?', 'Ils donnent une vision d\'ensemble du réseau : répartition du chiffre d\'affaires, des résultats, des ratios entre agences. C\'est une lecture synthétique, utile pour préparer une présentation à la direction ou repérer une tendance générale.'],
    ['Comment fonctionnent les périodes de paie ?', 'Les périodes de paie découpent l\'année selon votre calendrier de paie réel, qui ne coïncide pas toujours avec les mois civils. SOMA en tient compte pour rattacher les charges à la bonne période. C\'est ce qui explique que la masse salariale d\'un mois ne corresponde pas exactement au temps travaillé de ce mois.'],
    ['Pourquoi la masse salariale ne colle pas au temps travaillé du mois ?', 'Parce que la paie suit ses propres périodes, décalées par rapport aux mois civils, et parce qu\'elle intègre des éléments variables (heures supplémentaires, indemnités) rattachés à des dates de versement. SOMA reconstitue la masse salariale au plus près de la réalité de paie, pas du simple temps travaillé.'],
    ['Que comprend exactement la masse salariale du prévisionnel ?', 'Elle intègre les salaires de base du personnel roulant et improductif, les heures supplémentaires valorisées selon leur majoration réelle (25% ou 50%), les indemnités, et les charges patronales. C\'est le coût complet du personnel, pas seulement les salaires bruts.'],
    ['Mon rôle dans le circuit de validation ?', 'Le contrôleur de gestion et le directeur financier valident ensemble à la deuxième étape du circuit, après le directeur régional. Les deux doivent valider pour que le budget passe à la Direction. Votre onglet de validation vous montre les budgets qui attendent votre décision.'],
    ['Comment exporter la consolidation pour la direction ?', 'La fonction d\'export de la consolidation génère une vue agrégée de l\'ensemble du réseau, prête à être transmise à la direction. Elle rassemble les chiffres des agences validées en une synthèse unique.'],
  ],
  valideur: [
    ['Comment fonctionne le circuit de validation collégial ?', 'Le circuit comporte trois étapes successives. D\'abord le directeur régional de l\'agence. Puis le contrôleur de gestion et le directeur financier ensemble. Enfin la Direction (direction générale et directeurs opérationnels) ensemble. À chaque étape, tous les valideurs concernés doivent valider pour passer à la suivante. Un seul refus, à n\'importe quelle étape, renvoie le budget au responsable pour correction.'],
    ['Quels budgets dois-je valider ?', 'Votre écran de validation ne vous montre que les budgets qui attendent votre décision, à votre étape du circuit. Vous ne voyez pas ceux qui sont encore aux étapes précédentes ni ceux que vous avez déjà traités. Un badge vous indique combien de budgets vous attendent.'],
    ['Comment lire la fiche de décisions d\'un budget ?', 'Chaque budget se présente comme une fiche en trois temps : d\'où part l\'agence, les décisions prises par le responsable, et le résultat qui en découle. Vous ne validez pas des chiffres, vous validez des choix opérationnels : une ambition de chiffre d\'affaires, un mouvement d\'effectif, un taux d\'absentéisme, une charge d\'heures supplémentaires. La fiche vous permet de comprendre le budget en quelques secondes.'],
    ['Que veulent dire les verdicts sur la fiche ?', 'À côté de chaque décision, SOMA pose un repère. Quand il dispose d\'une référence sûre, il juge : par exemple un absentéisme optimiste par rapport au taux calculé par le service RH. Quand il n\'a pas de seuil certain, il se contente de situer la décision par rapport à la médiane du réseau ou à l\'historique de l\'agence. Les points d\'attention sont signalés pour que vous sachiez où porter votre jugement.'],
    ['Pourquoi mon commentaire est-il obligatoire ?', 'Parce qu\'une décision de validation engage. Un commentaire, qu\'il accompagne une validation ou un refus, laisse une trace de votre raisonnement. En cas de refus, il indique au responsable ce qu\'il doit corriger. En cas de validation, il documente ce que vous avez accepté et pourquoi.'],
    ['Que se passe-t-il quand je valide ?', 'Votre validation est enregistrée avec la date et votre commentaire. Si tous les valideurs de votre étape ont validé, le budget passe à l\'étape suivante. Quand la dernière étape valide, le budget est définitivement adopté pour l\'exercice.'],
    ['Que se passe-t-il si je refuse ?', 'Le budget retourne immédiatement au responsable à l\'état brouillon, et toutes les validations déjà obtenues sont effacées. Le responsable voit votre motif de refus, corrige, et resoumet. Un nouveau cycle de validation démarre alors depuis le directeur régional. Un refus est donc une décision qui a du poids : d\'où l\'importance du commentaire.'],
    ['L\'historique des refus est-il conservé ?', 'Oui. Même après une resoumission, SOMA garde la trace des refus précédents et de leurs motifs. Si un budget a déjà été refusé, vous le voyez sur sa fiche, avec la raison. Cela vous permet de vérifier si le responsable a bien corrigé ce qui avait été signalé.'],
    ['Puis-je consulter le budget en détail avant de décider ?', 'Oui. Le bouton pour voir tous les écrans ouvre le budget complet en lecture seule. Vous parcourez l\'objectif, l\'équipe, la présence, le prévisionnel et la synthèse exactement comme le responsable les a construits, sans rien pouvoir modifier. Un bandeau vous rappelle que vous êtes en consultation.'],
    ['Qu\'est-ce que le coût du choix affiché sur certains budgets ?', 'Le responsable peut avoir choisi de répartir les congés autrement que l\'optimum calculé, par exemple pour le climat social de son équipe. SOMA chiffre le surcoût de ce choix. Ce n\'est pas une faute : c\'est un arbitrage humain que vous êtes invité à valider en connaissance de cause.'],
    ['Le responsable voit-il mes commentaires ?', 'Oui, en cas de refus : votre motif lui est affiché pour qu\'il sache quoi corriger. C\'est le sens même du commentaire obligatoire : rendre votre décision utile et compréhensible pour celui qui reçoit le budget.'],
    ['Comment comparer les agences entre elles ?', 'Au-delà des budgets à valider, la consolidation et la vue réseau vous permettent de situer chaque agence par rapport aux autres. Une décision de budget se juge toujours mieux avec le contexte du réseau en tête.'],
  ],
  admin: [
    ['Comment créer un compte ?', 'Depuis l\'écran d\'administration, la fonction de création de compte vous permet d\'ajouter un utilisateur, de lui attribuer un rôle (responsable, contrôleur de gestion, directeur régional, direction) et, le cas échéant, de le rattacher à une agence ou une région.'],
    ['Comment tester les différents profils ?', 'Depuis l\'écran d\'administration, vous pouvez basculer dans la vue de n\'importe quel rôle pour voir SOMA exactement comme cet utilisateur le voit. Un bandeau orange en haut de l\'écran vous rappelle que vous êtes en simulation et vous permet de revenir à tout moment à l\'administration.'],
    ['Comment fonctionne l\'affectation des DR aux agences ?', 'L\'écran d\'affectation associe chaque agence à son directeur régional. Cette affectation détermine qui valide le budget de l\'agence à la première étape du circuit. Une agence sans DR affecté ne pourra pas être validée : l\'écran vous signale celles qui restent à affecter.'],
    ['Comment réinitialiser un mot de passe ?', 'La gestion des comptes permet de déclencher une réinitialisation de mot de passe pour un utilisateur. Il recevra les instructions pour définir un nouveau mot de passe.'],
    ['Comment supprimer un compte ?', 'Depuis la gestion des utilisateurs, vous pouvez supprimer un compte. Soyez prudent : cette action retire l\'accès de l\'utilisateur. Vérifiez qu\'aucun budget en cours ne dépend de lui avant de procéder.'],
    ['Les données sont-elles sauvegardées automatiquement ?', 'Oui. Toutes les saisies sont enregistrées automatiquement sur le serveur, en continu. Les utilisateurs n\'ont pas de manipulation à faire pour conserver leur travail.'],
    ['Puis-je modifier un budget à la place d\'un responsable ?', 'L\'administration donne accès à la modification des budgets. Utilisez cette possibilité avec discernement : le budget appartient au responsable de l\'agence, et toute modification de votre part doit rester exceptionnelle et justifiée.'],
  ],
};

// Mapping role -> cle FAQ (repris de renderAide()).
export function faqKeyForRole(role) {
  if (role === 'rex') return 'rex';
  if (role === 'cg') return 'cg';
  if (role === 'admin') return 'admin';
  if (['dr', 'df', 'dg', 'pdg'].includes(role)) return 'valideur';
  return 'rex';
}

export const FAQ_ROLE_LABEL = {
  rex: "Responsable d'exploitation",
  cg: 'Controleur de gestion',
  valideur: 'Validation',
  admin: 'Administrateur'
};
